add constants and binary utils for binary trie
ApeWorX/py-trie pull request #11
Opened 2017-12-09 16:38 UTC by NIC619

### How was it fixed?
Add binary trie part 1: Add the constants and the binary encoding/decoding utilities(and tests) for binary trie

#### Cute Animal Picture

![Cute animal picture](https://i.pinimg.com/originals/81/b9/7c/81b97c783facd9fc94fed8e0d0d12ed2.jpg)

2017-12-09 16:53 UTC, pipermerriam commented on trie/utils/binaries.py
> +    if isinstance(value, int):
FYI, `isinstance(value, int)` will return truthy for `True` and `False`.  You can use `eth_utils.is_integer` if you need that kind of precision.

2017-12-10 03:21 UTC, NIC619 commented
@pipermerriam Thanks for the reminder. Replaced it with `is_integer` as a precaution.

2017-12-10 03:55 UTC, pipermerriam requested changes
I got curious and ended up trying out some ideas that I think improve both readability *and* performance.  Lemme know what you think.

2017-12-10 03:55 UTC, pipermerriam commented on trie/utils/binaries.py
> +def decode_from_bin(input_bin):
I just toyed with an alternate implementation of this.

```python
from eth_utils import (
    apply_to_return_value,
)
from cytoolz import (
    partition_all,
)


@apply_to_return_value(bytes)
def alt_decode_from_bin(input_bin):
    for chunk in partition_all(8, input_bin):
        yield sum(
            2**exp * bit
            for exp, bit
            in enumerate(reversed(chunk))
        )
```

Some *very* rudimentary benchmarking suggests it's about 30% faster than the current implementation.

2017-12-10 03:55 UTC, pipermerriam commented on trie/utils/binaries.py
> +def encode_to_bin(value):
Ended up also taking a stab at an alternate implementation of this.

```python
EXP = tuple(reversed(tuple(2**i for i in range(8))))


@apply_to_return_value(bytes)
def alt_encode_to_bin(value):
    for char in value:
        for exp in EXP:
            if char & exp:
                yield True
            else:
                yield False
```

Benchmarking suggests it's 5-20% faster than the current implementation and I think it's a bit easier to read as well.

2017-12-10 03:58 UTC, pipermerriam approved these changes

2017-12-10 08:30 UTC, NIC619 commented
Though I didn't go too much into performance part, it definitely looks much cleaner. Will definitely try to adhere to this pattern.

2017-12-10 08:38 UTC, NIC619 commented
Merged with new binary encoding/decoding.

2017-12-10 08:39 UTC, merged