add node parsing/encoding/decoding utils and tests
ApeWorX/py-trie pull request #12
Opened 2017-12-10 16:36 UTC by NIC619

### How was it fixed?
Add binary trie node parsing/encoding/decoding utilities and tests

#### Cute Animal Picture

![Cute animal picture](https://www.ihdimages.com/wp-content/uploadsktz/2014/09/cute_animal_wallpaper_background.jpg)

2017-12-11 03:43 UTC, pipermerriam requested changes
I think it would be prudent to also include tests for the non-failure cases for each of these utilities.  They serve as both a spec for future contributors to the codebase as well as simply ensuring that these tools work for the basic use cases we expect.

2017-12-11 03:43 UTC, pipermerriam commented on tests/test_nodes_utils.py
> +    except InvalidNode:
This test would currently pass if any of the test cases above did not raise `InvalidNode`

The way to test this type of thing using pytest is using `pytest.raises`

```python
with pytest.raises(InvalidNode):
    parse_node(node)
```

Tests written this way will fail if the provided exception is not raised.

2017-12-11 03:43 UTC, pipermerriam commented on tests/test_nodes_utils.py
> +    except ValidationError:
Same note about how to test exception raising.

2017-12-11 03:43 UTC, pipermerriam commented on tests/test_nodes_utils.py
> +    except ValidationError:
Same note about exception raising tests.

2017-12-11 03:43 UTC, pipermerriam commented on trie/utils/nodes.py
> +        return node[1:33], node[33:], BRANCH_TYPE
I'm curious about the choice to return the type as the 3rd parameter.  Maybe my intuition is off but I would have expected it to be the first parameter.  Not sure why, but it feels more correct.  

Thoughts? (I'm not saying this is wrong, just curious if there is a reason for the current ordering)

2017-12-11 03:43 UTC, pipermerriam commented on trie/utils/nodes.py
> +    return bytes([KV_TYPE]) + encode_from_bin_keypath(keypath) + child_node_hash
We can probably gain some *minor* performance improvements if we stored `KV_NODE_PREFIX = bytes([KV_TYPE])` as a constant.

Same for the other prefixes.

2017-12-11 16:52 UTC, NIC619 commented
1. added test cases with valid input
or they can be combined into one test case like
```
@pytest.mark.parametrize(
    'valid_node,invalid_node',
    (
        (b"\x02value", b"\x02"),
    ),
)
def test_binary_trie_node_parsing(valid_node, invalid_node)
```
for cleanliness

2. added constant node type prefix and change arrangement of returned data of `parse_node`

2017-12-11 17:05 UTC, pipermerriam approved these changes
RE the comments suggesting improvements to the tests.

If you are in a hurry and need to move this forward, feel free to add some `TODO` comments to the code and open up an corresponding issue on github indicating that this test suite can be further fleshed out.

2017-12-11 17:05 UTC, pipermerriam commented on tests/test_nodes_utils.py
> +    parse_node(valid_node)
What do you think about adding assertions that the return of this function is returning the expected values?  Seems like a small addition that would improve this test quite a bit.

2017-12-11 17:05 UTC, pipermerriam commented on tests/test_nodes_utils.py
> +    encode_kv_node(keypath, valid_value)
Same suggestion here about adding some assertions about the value returned from this function.

2017-12-11 17:05 UTC, pipermerriam commented on tests/test_nodes_utils.py
> +    encode_branch_node(left_child_node_hash, right_child_node_hash)
Same here about adding assertions for the return value of this function

2017-12-11 17:05 UTC, pipermerriam commented on tests/test_nodes_utils.py
> +    encode_leaf_node(valid_value)
Same here about adding assertions for the return value of this function

2017-12-12 08:09 UTC, NIC619 commented
@pipermerriam test suites updated. Requesting a review. Thanks

2017-12-12 14:29 UTC, pipermerriam approved these changes

2017-12-13 07:57 UTC, merged