Add binary trie module part 1
ApeWorX/py-trie pull request #8
Opened 2017-12-05 17:30 UTC by NIC619

### How was it fixed?
Add binary trie part 1: Add the constants and the binary encoding/decoding utilities for binary trie

#### Cute Animal Picture

![Cute animal picture](http://cdn.attackofthecute.com/May-08-2012-04-07-41-dfbdgbhgnn.jpg)

2017-12-05 18:06 UTC, pipermerriam commented
There are some minor linting error that CI is going to complain about.  You can find/test these locally using `tox flake8` or `flake8 trie` (you may need to install `tox` or `flake8` in your python environment).  Otherwise looks like a good start.  Please assign me for review or add the "Ready for Review" label to anything that needs to be reviewed.

2017-12-06 05:32 UTC, NIC619 commented
`flake8`'ed and reviewer assigned. Thanks!

2017-12-06 16:19 UTC, pipermerriam requested changes
Can you get tests added for the utility functions you added.  Lets be sure they behave as expected as well as the tests serving as a spec for how they should be used.

2017-12-06 16:19 UTC, pipermerriam commented on trie/constants.py
> +PREFIX_00 = TWO_BITS[0]
*minor nitpick*

I would *suggest* not making this constant reference the previous one and just declaring it independently in the spirit of decoupling

2017-12-09 16:42 UTC, NIC619 commented
Closed in favor of #11

2017-12-09 16:42 UTC, closed without merging